export const securityData = {
  servers: [
    {
      id: 'mcp-server-web-search',
      name: 'Web Search MCP',
      slug: 'web-search',
      version: '1.2.0',
      securityLint: {
        score: 92.2,
        totalChecks: 10,
        passedChecks: 9,
        criticalFailures: [],
        providers: {
          mcpValidator: {
            version: 'v0.3.1',
            runId: 'val-2025-09-27T12:34:56Z',
          },
          mcpScan: {
            version: 'v0.3.13',
            mode: ['scan', 'proxy'],
            runId: 'scan-2025-09-27T12:35:21Z',
          },
        },
        scoring: {
          weights: { critical: 10, high: 6, medium: 3, low: 1 },
          capOnCriticalFailure: 79.9,
        },
        checks: {
          'VAL-HTTP-ORIGIN': {
            name: 'Origin validation (DNS‑rebinding defense)',
            source: 'mcp-validator',
            category: 'transport',
            severity: 'critical',
            weight: 10,
            satisfied: true,
            scoreContribution: 10,
            evidence: {
              type: 'httpTrace',
              request: {
                method: 'POST',
                path: '/messages',
                headers: { Origin: 'https://evil.example' },
              },
              response: {
                status: 401,
                headers: { 'WWW-Authenticate': 'Bearer realm="mcp-server"' },
              },
              asserts: ['Origin not allowed; challenge returned'],
            },
          },
          'VAL-OAUTH-BEARER': {
            name: 'OAuth 2.1 Bearer token enforcement',
            source: 'mcp-validator',
            category: 'authz',
            severity: 'critical',
            weight: 10,
            satisfied: true,
            scoreContribution: 10,
            evidence: {
              type: 'validatorAssertion',
              testId: 'http_auth_bearer',
              logRef: 'reports/http_compliance.json',
              details: {
                validTokenStatus: 200,
                invalidTokenStatus: 401,
                challengeHeader: 'Bearer realm="mcp-server"',
              },
            },
          },
          'VAL-OAUTH-SCOPES': {
            name: 'Scope enforcement',
            source: 'mcp-validator',
            category: 'authz',
            severity: 'critical',
            weight: 10,
            satisfied: true,
            scoreContribution: 10,
            evidence: {
              type: 'validatorAssertion',
              testId: 'oauth_scopes',
              logRef: 'reports/http_compliance.json',
              details: {
                requiredScopes: ['web:read'],
                cases: [
                  { scopes: [], status: 403 },
                  { scopes: ['web:read'], status: 200 },
                ],
              },
            },
          },
          'VAL-HTTP-NO-BATCH': {
            name: 'JSON‑RPC batching rejected (2025‑06‑18)',
            source: 'mcp-validator',
            category: 'protocol',
            severity: 'high',
            weight: 6,
            satisfied: true,
            scoreContribution: 6,
            evidence: {
              type: 'validatorAssertion',
              testId: 'no_batching_2025_06_18',
              logRef: 'reports/http_compliance.json',
              details: {
                request: [
                  { jsonrpc: '2.0', id: 1, method: 'ping' },
                  { jsonrpc: '2.0', id: 2, method: 'tools/list' },
                ],
                error: { code: -32600, message: 'Batching not supported' },
              },
            },
          },
          'VAL-TOOLS-SCHEMA': {
            name: 'Tool input/output schema enforced',
            source: 'mcp-validator',
            category: 'tools',
            severity: 'medium',
            weight: 3,
            satisfied: true,
            scoreContribution: 3,
            evidence: {
              type: 'validatorAssertion',
              testId: 'tools_schema',
              logRef: 'reports/tools_schema.json',
              details: {
                tool: 'advanced_query',
                inputValidated: true,
                outputValidated: true,
              },
            },
          },
          'SCAN-E001': {
            name: 'Tool poisoning / prompt injection (descriptions)',
            source: 'mcp-scan',
            category: 'supply_chain',
            severity: 'critical',
            weight: 10,
            satisfied: true,
            scoreContribution: 10,
            evidence: {
              type: 'scanReport',
              issue: 'E001',
              summary: { toolsAnalyzed: 3, issuesFound: 0 },
              reportPath: 'scan/mcp-scan.json',
            },
          },
          'SCAN-W003': {
            name: 'Entity integrity (pinning / rug pull)',
            source: 'mcp-scan',
            category: 'supply_chain',
            severity: 'high',
            weight: 6,
            satisfied: true,
            scoreContribution: 6,
            evidence: {
              type: 'integrity',
              entity: { kind: 'tool', name: 'basic_search' },
              hashAlg: 'sha256',
              prevHash: 'c1b2f39a...9f',
              currHash: 'c1b2f39a...9f',
              firstSeen: '2025-01-12T09:10:00Z',
            },
          },
          'SCAN-PII-LEAK': {
            name: 'PII in tool outputs (proxy)',
            source: 'mcp-scan',
            category: 'runtime',
            severity: 'high',
            weight: 6,
            satisfied: false,
            scoreContribution: 0,
            evidence: {
              type: 'proxyGuardrail',
              rule: 'pii',
              action: 'block',
              count: 2,
              spans: [
                { start: 34, end: 49 },
                { start: 115, end: 129 },
              ],
              sample: 'Found email alice@example.com and phone +1-555-123-4567',
              callId: 'call-7cdb',
              server: 'web-search',
              tool: 'advanced_query',
            },
          },
          'SCAN-SECRETS-LEAK': {
            name: 'Secrets in tool outputs (proxy)',
            source: 'mcp-scan',
            category: 'runtime',
            severity: 'high',
            weight: 6,
            satisfied: true,
            scoreContribution: 6,
            evidence: {
              type: 'proxyGuardrail',
              rule: 'secrets',
              action: 'log',
              count: 0,
              callId: '-',
              server: 'web-search',
              tool: '-',
            },
          },
          'SCAN-TF001': {
            name: 'Toxic Flow: Data leak chain',
            source: 'mcp-scan',
            category: 'flow',
            severity: 'critical',
            weight: 10,
            satisfied: true,
            scoreContribution: 10,
            evidence: {
              type: 'toxicFlow',
              flowId: 'tf-none',
              kind: 'TF001',
              nodes: [],
              edges: [],
              detected: false,
            },
          },
        },
        vizDataset: [
          {
            id: 'VAL-HTTP-ORIGIN',
            label: 'Origin validation',
            category: 'Transport',
            severity: 'critical',
            weight: 10,
            satisfied: true,
            scoreContribution: 10,
            provider: 'mcp-validator',
          },
          {
            id: 'VAL-OAUTH-BEARER',
            label: 'Bearer token',
            category: 'AuthZ',
            severity: 'critical',
            weight: 10,
            satisfied: true,
            scoreContribution: 10,
            provider: 'mcp-validator',
          },
          {
            id: 'VAL-OAUTH-SCOPES',
            label: 'Scope enforcement',
            category: 'AuthZ',
            severity: 'critical',
            weight: 10,
            satisfied: true,
            scoreContribution: 10,
            provider: 'mcp-validator',
          },
          {
            id: 'VAL-HTTP-NO-BATCH',
            label: 'No batching',
            category: 'Protocol',
            severity: 'high',
            weight: 6,
            satisfied: true,
            scoreContribution: 6,
            provider: 'mcp-validator',
          },
          {
            id: 'VAL-TOOLS-SCHEMA',
            label: 'Schema enforced',
            category: 'Tools',
            severity: 'medium',
            weight: 3,
            satisfied: true,
            scoreContribution: 3,
            provider: 'mcp-validator',
          },
          {
            id: 'SCAN-E001',
            label: 'Prompt injection',
            category: 'SupplyChain',
            severity: 'critical',
            weight: 10,
            satisfied: true,
            scoreContribution: 10,
            provider: 'mcp-scan',
          },
          {
            id: 'SCAN-W003',
            label: 'Integrity pinning',
            category: 'SupplyChain',
            severity: 'high',
            weight: 6,
            satisfied: true,
            scoreContribution: 6,
            provider: 'mcp-scan',
          },
          {
            id: 'SCAN-PII-LEAK',
            label: 'PII leak',
            category: 'Runtime',
            severity: 'high',
            weight: 6,
            satisfied: false,
            scoreContribution: 0,
            provider: 'mcp-scan',
          },
          {
            id: 'SCAN-SECRETS-LEAK',
            label: 'Secrets leak',
            category: 'Runtime',
            severity: 'high',
            weight: 6,
            satisfied: true,
            scoreContribution: 6,
            provider: 'mcp-scan',
          },
          {
            id: 'SCAN-TF001',
            label: 'Toxic flow (data)',
            category: 'Flow',
            severity: 'critical',
            weight: 10,
            satisfied: true,
            scoreContribution: 10,
            provider: 'mcp-scan',
          },
        ],
        vizByCategory: [
          { category: 'Transport', earned: 10, max: 10, percent: 100.0 },
          { category: 'AuthZ', earned: 20, max: 20, percent: 100.0 },
          { category: 'Protocol', earned: 6, max: 6, percent: 100.0 },
          { category: 'Tools', earned: 3, max: 3, percent: 100.0 },
          { category: 'SupplyChain', earned: 16, max: 16, percent: 100.0 },
          { category: 'Runtime', earned: 6, max: 12, percent: 50.0 },
          { category: 'Flow', earned: 10, max: 10, percent: 100.0 },
        ],
      },
    },
  ],
  metadata: {
    version: '1.1.0',
    generatedAt: '2025-09-27T12:40:00Z',
    totalServers: 1,
  },
}