#!/usr/bin/env bash
set -euo pipefail

MCPT_ROOT="$(pwd)"
PARENT_DIR="$(dirname "$MCPT_ROOT")"

EH(){
  printf '%s\n' "$*" 1>&2
}

EH "Cloning mcp-scan and mcp-validator alongside $(basename "$MCPT_ROOT")…"
cd "$PARENT_DIR"

if [ ! -d "mcp-scan" ]; then
  git clone https://github.com/invariantlabs-ai/mcp-scan.git
else
  EH "mcp-scan already present, skipping clone."
fi

if [ ! -d "mcp-validator" ]; then
  git clone https://github.com/Janix-ai/mcp-validator.git
else
  EH "mcp-validator already present, skipping clone."
fi

cd "$MCPT_ROOT"

MAC_CACHE_DIR="$HOME/Library/Application Support/mcptesting/mcp-scan"
mkdir -p "$MAC_CACHE_DIR"

touch .env
cat > .env <<EOF_ENV
# Automatically generated by setup script
MCP_SCAN_PROJECT_ROOT=$PARENT_DIR/mcp-scan
MCP_VALIDATOR_PROJECT_ROOT=$PARENT_DIR/mcp-validator
MCP_SCAN_STORAGE_ROOT=$MAC_CACHE_DIR
EOF_ENV

EH "Created/updated .env with macOS defaults:"
cat .env
EH "To load these variables: source .env"
